version: "3"

services:
  app: 
    build:
      context: .
    ports:
      - "8000:8000"
    # Map the ./app/ directory in our project into the Docker container
    volumes:
      - ./app:/app
    # Run Django developer server on port 8000 (mapped as above)
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      # The name of the host with the database
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
